kind: Service
apiVersion: v1
metadata:
  name: revolution-blog-frontend
  namespace: default
  labels:
    cis.f5.com/as3-tenant: "Revolution"
    cis.f5.com/as3-app: "blog"
    cis.f5.com/as3-pool: "web_pool"
spec:
  type: NodePort
  selector:
    app: web-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80